enum TokenType {
    PLUS, MINUS, TIMES, DIVIDE, LPAREN, RPAREN, SEMICOLON, COLON, ASSIGN, DOT, COMMA,
    INTEGER_CONST, REAL_CONST, IDENTIFIER, MODULO,
    PROGRAM, BEGIN, END, VAR, INTEGER, PROCEDURE, REAL, QUOTE, LEFTDOUBLEQUOTE, RIGHTDOUBLEQUOTE, EOF
}
