enum TokenType {
    PLUS, MINUS, TIMES, DIVIDE, LPAREN, RPAREN, SEMICOLON, COLON, ASSIGN, DOT, COMMA,
    INTEGER_CONST, REAL_CONST, IDENTIFIER, MODULO,
    PROGRAM, BEGIN, END, VAR, INTEGER, PROCEDURE, REAL, QUOTE, LEFTDOUBLEQUOTE, RIGHTDOUBLEQUOTE,
    BOOLEAN, FUNCTION, IF, ELSE, THEN, WHILE, DO, FOR, TO, DOWNTO, ARRAY, OF, RECORD, CASE, REPEAT, UNTIL,
    CONST, TYPE, DIV, MOD, AND, OR, NOT, BOOLEAN_CONST, BOOLEAN_OPERATOR,EOF
}
